title:            Michael Watts
description:      Website of Michael Watts, a web developer in Surrey, UK
disqus_shortname: disqus_V6ccNgzKE5
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url: http://michaelwatts.me

# Owner/author information
owner:
  name:           Michael Watts
  avatar:         df75fece89f48dab15f6e458d73b0915.jpg
  bio:            "A web developer from Surrey in the UK."
  email:          hello@michaelwatts.me
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:
  github:         altescape
  stackexchange:  http://stackoverflow.com/users/1945990/mjwatts
  linkedin:       mwattsweb
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    113239679855361194218

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: AngularJS
    url: https://angularjs.org/
    external: true
  - title: javascriptissexy.com
    url: http://javascriptissexy.com/
    external: true
  - title: DailyJS
    url: http://dailyjs.com/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5
