name = "Michael Watts"
license = "GPL-3.0 License"
licenselink = "https://github.com/altescape/michaelwatts.me-website/LICENSE.md"
description = "Website of Michael Watts"
min_version = "0.101.0"

# The home page of the theme, where the source can be found.
homepage = "https://michaelwatts.me"

tags = ["blog", "personal", "dark", "dark-mode", "light", "minimal"]
features = ["blog", "katex", "table-of-contents", "tabs", "dark-mode", "series"]

[author]
    name = "Michael"
    homepage = "https://michaelwatts.me"
